import type { RowDetailsModel } from '@/lib/row-details';

export type DemoTabId =
  | 'companies'
  | 'people'
  | 'news'
  | 'signals'
  | 'marketReports'
  | 'patents'
  | 'researchPapers';

export type DemoColumn = {
  key: string;
  label: string;
  align?: 'left' | 'right' | 'center';
};

export type DemoTabConfig = {
  id: DemoTabId;
  label: string;
  description: string;
  columns: DemoColumn[];
  rows: Array<Record<string, string | number>>;
  chips?: string[];
  getSidebarModel: (row: Record<string, string | number>) => RowDetailsModel;
};

const makeRows = <T extends Record<string, string | number>>(rows: T[]) => rows;

const companiesRows = makeRows([
  {
    id: 'co-1',
    company: 'Noon',
    location: 'UAE',
    founded: 2017,
    employees: '1000+',
    status: 'Active',
    match: 'Match',
    revenue: '$500M+',
    people: 12,
    news: 8,
    summary: 'Marketplace leader expanding across MENA with rapid category growth.',
  },
  {
    id: 'co-2',
    company: 'Careem',
    location: 'UAE',
    founded: 2012,
    employees: '5000+',
    status: 'Active',
    match: 'Not Match',
    revenue: '$1B+',
    people: 25,
    news: 15,
    summary: 'Super app with strong logistics footprint and payment expansion.',
  },
  {
    id: 'co-3',
    company: 'Tabby',
    location: 'Saudi Arabia',
    founded: 2019,
    employees: '400+',
    status: 'Active',
    match: 'Match',
    revenue: '$120M+',
    people: 8,
    news: 6,
    summary: 'Buy-now-pay-later leader growing enterprise partnerships.',
  },
  {
    id: 'co-4',
    company: 'Mamo',
    location: 'UAE',
    founded: 2019,
    employees: '200+',
    status: 'Active',
    match: 'Neutral',
    revenue: '$30M+',
    people: 5,
    news: 3,
    summary: 'SMB payments platform building regional SMB reach.',
  },
  {
    id: 'co-5',
    company: 'Zbooni',
    location: 'Jordan',
    founded: 2017,
    employees: '120+',
    status: 'Active',
    match: 'Match',
    revenue: '$12M+',
    people: 4,
    news: 2,
    summary: 'Conversational commerce platform focused on WhatsApp storefronts.',
  },
  {
    id: 'co-6',
    company: 'Sarwa',
    location: 'UAE',
    founded: 2017,
    employees: '150+',
    status: 'Active',
    match: 'Match',
    revenue: '$18M+',
    people: 3,
    news: 4,
    summary: 'Wealthtech platform scaling advisory across GCC.',
  },
  {
    id: 'co-7',
    company: 'Tamara',
    location: 'Saudi Arabia',
    founded: 2020,
    employees: '500+',
    status: 'Active',
    match: 'Match',
    revenue: '$90M+',
    people: 10,
    news: 7,
    summary: 'Consumer finance leader with rapid merchant adoption.',
  },
  {
    id: 'co-8',
    company: 'Rain',
    location: 'Bahrain',
    founded: 2019,
    employees: '90+',
    status: 'Active',
    match: 'Neutral',
    revenue: '$8M+',
    people: 2,
    news: 3,
    summary: 'Crypto platform expanding regulated products in GCC.',
  },
  {
    id: 'co-9',
    company: 'YAP',
    location: 'UAE',
    founded: 2021,
    employees: '60+',
    status: 'Active',
    match: 'Match',
    revenue: '$5M+',
    people: 2,
    news: 1,
    summary: 'Digital banking platform focused on embedded finance.',
  },
  {
    id: 'co-10',
    company: 'Lean',
    location: 'Saudi Arabia',
    founded: 2019,
    employees: '200+',
    status: 'Active',
    match: 'Match',
    revenue: '$25M+',
    people: 6,
    news: 5,
    summary: 'Open banking infrastructure scaling across regional banks.',
  },
  {
    id: 'co-11',
    company: 'BitOasis',
    location: 'UAE',
    founded: 2016,
    employees: '120+',
    status: 'Active',
    match: 'Neutral',
    revenue: '$15M+',
    people: 4,
    news: 3,
    summary: 'Crypto exchange with institutional partnerships.',
  },
  {
    id: 'co-12',
    company: 'PayTabs',
    location: 'Saudi Arabia',
    founded: 2014,
    employees: '350+',
    status: 'Active',
    match: 'Match',
    revenue: '$45M+',
    people: 9,
    news: 6,
    summary: 'Payments gateway supporting cross-border commerce.',
  },
]);

const peopleRows = makeRows([
  {
    id: 'pe-1',
    name: 'Sarah Chen',
    company: 'Tabby',
    role: 'VP Growth',
    location: 'Dubai, UAE',
    email: 'sarah.chen@tabby.ai',
    match: 'Match',
    intents: 4,
    notes: 'Leading expansion partnerships across GCC.',
  },
  {
    id: 'pe-2',
    name: 'Omar Khaled',
    company: 'Careem',
    role: 'Head of Product',
    location: 'Dubai, UAE',
    email: 'omar.khaled@careem.com',
    match: 'Neutral',
    intents: 3,
    notes: 'Recently launched new payments feature set.',
  },
  {
    id: 'pe-3',
    name: 'Lisa Wang',
    company: 'Noon',
    role: 'Director, Ops',
    location: 'Dubai, UAE',
    email: 'lisa.wang@noon.com',
    match: 'Match',
    intents: 5,
    notes: 'Scaling fulfillment partner network.',
  },
  {
    id: 'pe-4',
    name: 'Ahmed Hassan',
    company: 'Lean',
    role: 'CTO',
    location: 'Riyadh, Saudi Arabia',
    email: 'ahmed.hassan@lean.sa',
    match: 'Match',
    intents: 6,
    notes: 'Hiring data engineers, expanding API suite.',
  },
  {
    id: 'pe-5',
    name: 'Priya Sharma',
    company: 'Mamo',
    role: 'Head of Sales',
    location: 'Dubai, UAE',
    email: 'priya.sharma@mamo.com',
    match: 'Match',
    intents: 2,
    notes: 'Targeting SMB finance teams.',
  },
  {
    id: 'pe-6',
    name: 'Marco Silva',
    company: 'Tamara',
    role: 'Finance Lead',
    location: 'Riyadh, Saudi Arabia',
    email: 'marco.silva@tamara.com',
    match: 'Neutral',
    intents: 1,
    notes: 'Exploring new credit scoring tools.',
  },
  {
    id: 'pe-7',
    name: 'Noura Al-Farsi',
    company: 'Sarwa',
    role: 'Product Manager',
    location: 'Abu Dhabi, UAE',
    email: 'noura.alfarsi@sarwa.co',
    match: 'Match',
    intents: 4,
    notes: 'Building automated advisory workflows.',
  },
  {
    id: 'pe-8',
    name: 'David Lee',
    company: 'Zbooni',
    role: 'Head of Partnerships',
    location: 'Amman, Jordan',
    email: 'david.lee@zbooni.com',
    match: 'Match',
    intents: 3,
    notes: 'Expanding WhatsApp commerce integrations.',
  },
  {
    id: 'pe-9',
    name: 'Rana Idris',
    company: 'YAP',
    role: 'Growth Lead',
    location: 'Dubai, UAE',
    email: 'rana.idris@yap.com',
    match: 'Match',
    intents: 4,
    notes: 'Driving fintech partnerships and outbound.',
  },
  {
    id: 'pe-10',
    name: 'Faraz Khalid',
    company: 'Rain',
    role: 'CPO',
    location: 'Manama, Bahrain',
    email: 'faraz.khalid@rain.com',
    match: 'Neutral',
    intents: 2,
    notes: 'Launching new custody features.',
  },
  {
    id: 'pe-11',
    name: 'Dalia Nour',
    company: 'PayTabs',
    role: 'VP Marketing',
    location: 'Riyadh, Saudi Arabia',
    email: 'dalia.nour@paytabs.com',
    match: 'Match',
    intents: 5,
    notes: 'Running demand gen in KSA.',
  },
  {
    id: 'pe-12',
    name: 'Samir Nasser',
    company: 'BitOasis',
    role: 'Director, Strategy',
    location: 'Dubai, UAE',
    email: 'samir.nasser@bitoasis.net',
    match: 'Neutral',
    intents: 2,
    notes: 'Exploring enterprise product lines.',
  },
]);

const newsRows = makeRows([
  {
    id: 'ne-1',
    title: 'Noon raises $500M to expand fulfillment network',
    source: 'Reuters',
    date: '2026-01-10',
    company: 'Noon',
    match: 'Match',
    summary: 'Funding accelerates fulfillment and logistics scale across MENA.',
    significance: 8.8,
    relevance: 9.1,
  },
  {
    id: 'ne-2',
    title: 'Careem launches new payments suite',
    source: 'Bloomberg',
    date: '2026-01-08',
    company: 'Careem',
    match: 'Neutral',
    summary: 'Payments expansion includes new merchant tooling.',
    significance: 7.2,
    relevance: 7.9,
  },
  {
    id: 'ne-3',
    title: 'Tabby partners with regional banks',
    source: 'TechCrunch',
    date: '2026-01-06',
    company: 'Tabby',
    match: 'Match',
    summary: 'New partnerships broaden credit access.',
    significance: 7.9,
    relevance: 8.4,
  },
  {
    id: 'ne-4',
    title: 'Lean secures enterprise fintech clients',
    source: 'The National',
    date: '2026-01-05',
    company: 'Lean',
    match: 'Match',
    summary: 'Open banking adoption rises in KSA.',
    significance: 7.1,
    relevance: 8.0,
  },
  {
    id: 'ne-5',
    title: 'Mamo adds SMB credit products',
    source: 'Wamda',
    date: '2026-01-03',
    company: 'Mamo',
    match: 'Neutral',
    summary: 'New credit products target merchant adoption.',
    significance: 6.8,
    relevance: 7.0,
  },
  {
    id: 'ne-6',
    title: 'Tamara expands to new GCC markets',
    source: 'Arabian Business',
    date: '2026-01-02',
    company: 'Tamara',
    match: 'Match',
    summary: 'Expansion focuses on retail categories.',
    significance: 6.5,
    relevance: 7.5,
  },
  {
    id: 'ne-7',
    title: 'Sarwa launches AI-assisted advisory',
    source: 'Forbes MENA',
    date: '2026-01-01',
    company: 'Sarwa',
    match: 'Match',
    summary: 'New AI features target retail investors.',
    significance: 7.4,
    relevance: 8.2,
  },
  {
    id: 'ne-8',
    title: 'Rain receives regulatory approval in Qatar',
    source: 'CoinDesk',
    date: '2025-12-29',
    company: 'Rain',
    match: 'Neutral',
    summary: 'Approval unlocks institutional trading features.',
    significance: 6.2,
    relevance: 6.8,
  },
  {
    id: 'ne-9',
    title: 'YAP unveils embedded finance toolkit',
    source: 'TechCrunch',
    date: '2025-12-28',
    company: 'YAP',
    match: 'Match',
    summary: 'Toolkit simplifies fintech integrations for SMBs.',
    significance: 7.0,
    relevance: 7.7,
  },
  {
    id: 'ne-10',
    title: 'Zbooni doubles WhatsApp commerce volume',
    source: 'VentureBeat',
    date: '2025-12-27',
    company: 'Zbooni',
    match: 'Match',
    summary: 'New automation drives conversion increases.',
    significance: 6.4,
    relevance: 7.2,
  },
  {
    id: 'ne-11',
    title: 'PayTabs partners with Visa for new payouts',
    source: 'Finextra',
    date: '2025-12-26',
    company: 'PayTabs',
    match: 'Match',
    summary: 'Partnership improves payout speeds.',
    significance: 6.9,
    relevance: 7.6,
  },
  {
    id: 'ne-12',
    title: 'BitOasis launches institutional custody',
    source: 'CoinTelegraph',
    date: '2025-12-24',
    company: 'BitOasis',
    match: 'Neutral',
    summary: 'Custody product targets family offices.',
    significance: 6.1,
    relevance: 6.5,
  },
]);

const signalsRows = makeRows([
  {
    id: 'si-1',
    company: 'Noon',
    signalType: 'Funding',
    trigger: 'Series D round',
    date: '2026-01-10',
    score: 9.1,
    notes: 'SoftBank participation rumored.',
  },
  {
    id: 'si-2',
    company: 'Careem',
    signalType: 'Product',
    trigger: 'Payments rollout',
    date: '2026-01-08',
    score: 7.8,
    notes: 'New wallet features in KSA.',
  },
  {
    id: 'si-3',
    company: 'Tabby',
    signalType: 'Partnership',
    trigger: 'Bank integrations',
    date: '2026-01-06',
    score: 8.3,
    notes: 'Partnered with 3 regional banks.',
  },
  {
    id: 'si-4',
    company: 'Lean',
    signalType: 'Hiring',
    trigger: 'Data team expansion',
    date: '2026-01-05',
    score: 7.2,
    notes: 'Added 12 engineering roles.',
  },
  {
    id: 'si-5',
    company: 'Mamo',
    signalType: 'Expansion',
    trigger: 'New SME coverage',
    date: '2026-01-03',
    score: 6.7,
    notes: 'Launching in two new cities.',
  },
  {
    id: 'si-6',
    company: 'Tamara',
    signalType: 'Funding',
    trigger: 'Series C prep',
    date: '2026-01-02',
    score: 8.0,
    notes: 'Late-stage fundraising active.',
  },
  {
    id: 'si-7',
    company: 'Sarwa',
    signalType: 'Product',
    trigger: 'AI advisory',
    date: '2026-01-01',
    score: 7.6,
    notes: 'Feature rollout in beta.',
  },
  {
    id: 'si-8',
    company: 'Rain',
    signalType: 'Regulatory',
    trigger: 'New approval',
    date: '2025-12-29',
    score: 6.9,
    notes: 'Qatar sandbox acceptance.',
  },
  {
    id: 'si-9',
    company: 'YAP',
    signalType: 'Launch',
    trigger: 'Embedded finance',
    date: '2025-12-28',
    score: 7.3,
    notes: 'Toolkit launched for partners.',
  },
  {
    id: 'si-10',
    company: 'Zbooni',
    signalType: 'Growth',
    trigger: 'Volume surge',
    date: '2025-12-27',
    score: 6.5,
    notes: 'Transaction volume doubled.',
  },
  {
    id: 'si-11',
    company: 'PayTabs',
    signalType: 'Partnership',
    trigger: 'Visa payouts',
    date: '2025-12-26',
    score: 7.0,
    notes: 'New cross-border rails.',
  },
  {
    id: 'si-12',
    company: 'BitOasis',
    signalType: 'Product',
    trigger: 'Custody launch',
    date: '2025-12-24',
    score: 6.4,
    notes: 'Institutional custody go-live.',
  },
]);

const marketReportRows = makeRows([
  {
    id: 'mr-1',
    report: 'MENA Fintech Market Report 2026',
    publisher: 'McKinsey',
    region: 'MENA',
    date: '2026-01-12',
    tags: 'Payments, BNPL',
    insight: 'BNPL adoption up 40% YoY.',
    summary: 'Outlines growth drivers in digital payments and lending.',
  },
  {
    id: 'mr-2',
    report: 'GCC Digital Banking Outlook',
    publisher: 'Deloitte',
    region: 'GCC',
    date: '2026-01-09',
    tags: 'Banking, Retail',
    insight: 'Neobank churn drops with better onboarding.',
    summary: 'Benchmarks digital banks by onboarding and retention.',
  },
  {
    id: 'mr-3',
    report: 'SMB Payments Landscape',
    publisher: 'PwC',
    region: 'MENA',
    date: '2026-01-06',
    tags: 'SMB, Payments',
    insight: 'SMB payment volume growing 28% annually.',
    summary: 'Highlights digitization for SMEs in the Gulf.',
  },
  {
    id: 'mr-4',
    report: 'Open Banking Adoption Tracker',
    publisher: 'BCG',
    region: 'Saudi Arabia',
    date: '2026-01-04',
    tags: 'Open banking',
    insight: 'API usage doubled in the last 12 months.',
    summary: 'Analyzes regulatory adoption of open banking.',
  },
  {
    id: 'mr-5',
    report: 'Fintech Funding Radar',
    publisher: 'CB Insights',
    region: 'Global',
    date: '2026-01-02',
    tags: 'Funding',
    insight: 'MENA funding rebounds in Q4.',
    summary: 'Tracks funding dynamics and late-stage rounds.',
  },
  {
    id: 'mr-6',
    report: 'WealthTech in the Gulf',
    publisher: 'Gartner',
    region: 'GCC',
    date: '2025-12-30',
    tags: 'WealthTech',
    insight: 'Robo-advisors gain high-net-worth traction.',
    summary: 'Shifts in investor preferences across the Gulf.',
  },
  {
    id: 'mr-7',
    report: 'Payments Infrastructure Scorecard',
    publisher: 'KPMG',
    region: 'MENA',
    date: '2025-12-27',
    tags: 'Infrastructure',
    insight: 'Rail modernization boosts settlement speed.',
    summary: 'Examines payment rails modernization.',
  },
  {
    id: 'mr-8',
    report: 'Digital ID & KYC Trends',
    publisher: 'EY',
    region: 'MENA',
    date: '2025-12-24',
    tags: 'KYC, Compliance',
    insight: 'Digital ID adoption accelerates onboarding.',
    summary: 'Covers ID verification trends for fintech.',
  },
  {
    id: 'mr-9',
    report: 'Fintech M&A Watch',
    publisher: 'Bain',
    region: 'Global',
    date: '2025-12-22',
    tags: 'M&A',
    insight: 'Strategic M&A increasing across payments.',
    summary: 'Analysis of fintech consolidation patterns.',
  },
  {
    id: 'mr-10',
    report: 'Embedded Finance Outlook',
    publisher: 'BofA Research',
    region: 'Global',
    date: '2025-12-20',
    tags: 'Embedded finance',
    insight: 'Embedded finance revenue up 22% YoY.',
    summary: 'Forecast of embedded finance growth drivers.',
  },
  {
    id: 'mr-11',
    report: 'Lending Risk Trends',
    publisher: 'Moody\'s',
    region: 'MENA',
    date: '2025-12-18',
    tags: 'Lending',
    insight: 'Risk models adopting alternative data.',
    summary: 'Focuses on credit risk modeling innovations.',
  },
  {
    id: 'mr-12',
    report: 'Regional Fintech Talent Map',
    publisher: 'LinkedIn Insights',
    region: 'MENA',
    date: '2025-12-15',
    tags: 'Talent',
    insight: 'Hiring demand up 18% YoY.',
    summary: 'Talent distribution across fintech hubs.',
  },
]);

const patentRows = makeRows([
  {
    id: 'pa-1',
    title: 'Secure Payment Tokenization System',
    assignee: 'PayTabs',
    jurisdiction: 'US',
    filed: '2025-11-20',
    status: 'Pending',
    tags: 'Payments',
    summary: 'Tokenization method for cross-border payments.',
  },
  {
    id: 'pa-2',
    title: 'AI Fraud Detection for BNPL',
    assignee: 'Tabby',
    jurisdiction: 'EP',
    filed: '2025-11-02',
    status: 'Pending',
    tags: 'Risk',
    summary: 'Model-based fraud detection for installment plans.',
  },
  {
    id: 'pa-3',
    title: 'Open Banking API Gateway',
    assignee: 'Lean',
    jurisdiction: 'UK',
    filed: '2025-10-18',
    status: 'Filed',
    tags: 'API',
    summary: 'Gateway for bank data aggregation and consent.',
  },
  {
    id: 'pa-4',
    title: 'Digital Wallet with Spend Controls',
    assignee: 'Careem',
    jurisdiction: 'US',
    filed: '2025-10-01',
    status: 'Filed',
    tags: 'Wallet',
    summary: 'Spend control system for multi-user wallets.',
  },
  {
    id: 'pa-5',
    title: 'KYC Automation Pipeline',
    assignee: 'Mamo',
    jurisdiction: 'EP',
    filed: '2025-09-15',
    status: 'Granted',
    tags: 'Compliance',
    summary: 'Automation for AML and KYC verification.',
  },
  {
    id: 'pa-6',
    title: 'Blockchain Settlement for Remittances',
    assignee: 'Noon',
    jurisdiction: 'US',
    filed: '2025-09-01',
    status: 'Pending',
    tags: 'Remittance',
    summary: 'Blockchain-based settlement flow.',
  },
  {
    id: 'pa-7',
    title: 'Credit Risk Scoring via Alternative Data',
    assignee: 'Tamara',
    jurisdiction: 'US',
    filed: '2025-08-20',
    status: 'Filed',
    tags: 'Credit',
    summary: 'Risk score using alternative data sources.',
  },
  {
    id: 'pa-8',
    title: 'Secure Identity Wallet',
    assignee: 'YAP',
    jurisdiction: 'EP',
    filed: '2025-08-01',
    status: 'Pending',
    tags: 'Identity',
    summary: 'Identity wallet for secure onboarding.',
  },
  {
    id: 'pa-9',
    title: 'Merchant Analytics Dashboard',
    assignee: 'Zbooni',
    jurisdiction: 'US',
    filed: '2025-07-18',
    status: 'Filed',
    tags: 'Analytics',
    summary: 'Merchant analytics for commerce insights.',
  },
  {
    id: 'pa-10',
    title: 'Digital Asset Custody Vault',
    assignee: 'Rain',
    jurisdiction: 'UK',
    filed: '2025-07-01',
    status: 'Pending',
    tags: 'Custody',
    summary: 'Secure custody vault for digital assets.',
  },
  {
    id: 'pa-11',
    title: 'Real-time Payout Routing',
    assignee: 'BitOasis',
    jurisdiction: 'US',
    filed: '2025-06-20',
    status: 'Filed',
    tags: 'Payments',
    summary: 'Routing system for instant payouts.',
  },
  {
    id: 'pa-12',
    title: 'Subscription Billing Optimizer',
    assignee: 'Sarwa',
    jurisdiction: 'EP',
    filed: '2025-06-01',
    status: 'Granted',
    tags: 'Billing',
    summary: 'Optimizer for subscription payment flows.',
  },
]);

const researchRows = makeRows([
  {
    id: 'rp-1',
    title: 'Fintech Adoption in the Gulf',
    authors: 'H. Rahman, L. Wang',
    venue: 'IEEE Transactions',
    date: '2025-12-20',
    citations: 45,
    field: 'Fintech',
    summary: 'Survey of adoption drivers across GCC markets.',
  },
  {
    id: 'rp-2',
    title: 'Risk Models for BNPL Providers',
    authors: 'S. Chen, M. Silva',
    venue: 'ACM SIGKDD',
    date: '2025-12-10',
    citations: 62,
    field: 'Risk',
    summary: 'Alternative data improves default prediction.',
  },
  {
    id: 'rp-3',
    title: 'Open Banking API Performance',
    authors: 'A. Hassan, R. Idris',
    venue: 'Journal of Fintech',
    date: '2025-11-28',
    citations: 38,
    field: 'APIs',
    summary: 'Benchmark of latency and uptime across banks.',
  },
  {
    id: 'rp-4',
    title: 'Embedded Finance in MENA',
    authors: 'D. Lee, P. Sharma',
    venue: 'Nature Digital',
    date: '2025-11-20',
    citations: 29,
    field: 'Embedded finance',
    summary: 'Study on embedded finance adoption.',
  },
  {
    id: 'rp-5',
    title: 'KYC Automation with AI',
    authors: 'L. Wang, O. Khaled',
    venue: 'NeurIPS Workshops',
    date: '2025-11-02',
    citations: 55,
    field: 'Compliance',
    summary: 'AI-based KYC automation pipeline design.',
  },
  {
    id: 'rp-6',
    title: 'Payments Fraud Detection',
    authors: 'S. Nasser, N. Al-Farsi',
    venue: 'ICML',
    date: '2025-10-18',
    citations: 72,
    field: 'Fraud',
    summary: 'Deep learning model for anomaly detection.',
  },
  {
    id: 'rp-7',
    title: 'Digital Wallet Usability in GCC',
    authors: 'R. Idris, M. Silva',
    venue: 'CHI',
    date: '2025-10-02',
    citations: 19,
    field: 'UX',
    summary: 'Usability study across wallet products.',
  },
  {
    id: 'rp-8',
    title: 'Credit Scoring with Alternative Data',
    authors: 'A. Hassan, D. Nour',
    venue: 'AAAI',
    date: '2025-09-18',
    citations: 44,
    field: 'Credit',
    summary: 'Feature engineering for alternative signals.',
  },
  {
    id: 'rp-9',
    title: 'Fintech Talent Mobility',
    authors: 'S. Chen, L. Wang',
    venue: 'Harvard Data Science',
    date: '2025-09-01',
    citations: 16,
    field: 'Talent',
    summary: 'Talent movement patterns across hubs.',
  },
  {
    id: 'rp-10',
    title: 'Cross-border Payments Efficiency',
    authors: 'M. Silva, A. Rahman',
    venue: 'World Bank Working Paper',
    date: '2025-08-20',
    citations: 31,
    field: 'Payments',
    summary: 'Efficiency improvements in cross-border rails.',
  },
  {
    id: 'rp-11',
    title: 'Digital Lending in MENA',
    authors: 'P. Sharma, D. Lee',
    venue: 'IMF Notes',
    date: '2025-08-05',
    citations: 25,
    field: 'Lending',
    summary: 'Analysis of lending growth and risks.',
  },
  {
    id: 'rp-12',
    title: 'SMB Financing Access',
    authors: 'N. Al-Farsi, R. Idris',
    venue: 'Oxford Review',
    date: '2025-07-22',
    citations: 18,
    field: 'SMB finance',
    summary: 'SMB financing barriers across the region.',
  },
]);

export const demoTabs: DemoTabConfig[] = [
  {
    id: 'companies',
    label: 'Companies',
    description: 'Company lists enriched with revenue, size, and match signals.',
    columns: [
      { key: 'company', label: 'Company' },
      { key: 'location', label: 'Location' },
      { key: 'founded', label: 'Founded' },
      { key: 'employees', label: 'Employees' },
      { key: 'status', label: 'Status' },
      { key: 'match', label: 'Match' },
      { key: 'revenue', label: 'Revenue' },
      { key: 'people', label: 'People' },
      { key: 'news', label: 'News' },
    ],
    rows: companiesRows,
    getSidebarModel: (row) => ({
      title: String(row.company),
      fields: [
        { label: 'Location', value: row.location },
        { label: 'Founded', value: row.founded },
        { label: 'Employees', value: row.employees },
        { label: 'Status', value: row.status },
        { label: 'Revenue', value: row.revenue },
        { label: 'People', value: row.people },
        { label: 'News', value: row.news },
        { label: 'Match', value: row.match },
      ],
      summary: String(row.summary),
    }),
  },
  {
    id: 'people',
    label: 'People',
    description: 'Decision makers with enriched roles, emails, and intent signals.',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'company', label: 'Company' },
      { key: 'role', label: 'Role' },
      { key: 'location', label: 'Location' },
      { key: 'email', label: 'Email' },
      { key: 'match', label: 'Match' },
      { key: 'intents', label: 'Intents' },
    ],
    rows: peopleRows,
    getSidebarModel: (row) => ({
      title: String(row.name),
      fields: [
        { label: 'Role', value: row.role },
        { label: 'Email', value: row.email },
        { label: 'Company', value: row.company },
        { label: 'Location', value: row.location },
        { label: 'Match', value: row.match },
        { label: 'Intents', value: row.intents },
        { label: 'Notes', value: row.notes },
      ],
      summary: String(row.notes),
    }),
  },
  {
    id: 'news',
    label: 'News',
    description: 'Curated coverage scored by relevance and significance.',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'source', label: 'Source' },
      { key: 'date', label: 'Date' },
      { key: 'company', label: 'Company' },
      { key: 'match', label: 'Match' },
      { key: 'summary', label: 'Summary' },
    ],
    rows: newsRows,
    getSidebarModel: (row) => ({
      title: String(row.title),
      fields: [
        { label: 'Source', value: row.source },
        { label: 'Date', value: row.date },
        { label: 'Company', value: row.company },
        { label: 'Match', value: row.match },
        { label: 'Significance', value: row.significance },
        { label: 'Relevance', value: row.relevance },
      ],
      summary: String(row.summary),
    }),
  },
  {
    id: 'signals',
    label: 'Signals',
    description: 'Intent signals ranked by score and trigger.',
    columns: [
      { key: 'company', label: 'Company' },
      { key: 'signalType', label: 'Signal type' },
      { key: 'trigger', label: 'Trigger' },
      { key: 'date', label: 'Date' },
      { key: 'score', label: 'Score' },
      { key: 'notes', label: 'Notes' },
    ],
    rows: signalsRows,
    chips: ['Funding', 'Hiring', 'Launches', 'Coverage'],
    getSidebarModel: (row) => ({
      title: String(row.company),
      fields: [
        { label: 'Signal type', value: row.signalType },
        { label: 'Trigger', value: row.trigger },
        { label: 'Date', value: row.date },
        { label: 'Score', value: row.score },
        { label: 'Company', value: row.company },
        { label: 'Notes', value: row.notes },
      ],
      summary: String(row.notes),
    }),
  },
  {
    id: 'marketReports',
    label: 'Market Reports',
    description: 'Research reports with key insights and tags.',
    columns: [
      { key: 'report', label: 'Report' },
      { key: 'publisher', label: 'Publisher' },
      { key: 'region', label: 'Region' },
      { key: 'date', label: 'Date' },
      { key: 'tags', label: 'Tags' },
      { key: 'insight', label: 'Key insight' },
    ],
    rows: marketReportRows,
    getSidebarModel: (row) => ({
      title: String(row.report),
      fields: [
        { label: 'Publisher', value: row.publisher },
        { label: 'Region', value: row.region },
        { label: 'Date', value: row.date },
        { label: 'Tags', value: row.tags },
        { label: 'Key insight', value: row.insight },
      ],
      summary: String(row.summary),
    }),
  },
  {
    id: 'patents',
    label: 'Patents',
    description: 'Patent filings with status, jurisdiction, and tags.',
    columns: [
      { key: 'title', label: 'Patent title' },
      { key: 'assignee', label: 'Assignee' },
      { key: 'jurisdiction', label: 'Jurisdiction' },
      { key: 'filed', label: 'Filed' },
      { key: 'status', label: 'Status' },
      { key: 'tags', label: 'Tags' },
    ],
    rows: patentRows,
    getSidebarModel: (row) => ({
      title: String(row.title),
      fields: [
        { label: 'Assignee', value: row.assignee },
        { label: 'Filed', value: row.filed },
        { label: 'Status', value: row.status },
        { label: 'Jurisdiction', value: row.jurisdiction },
      ],
      summary: String(row.summary),
    }),
  },
  {
    id: 'researchPapers',
    label: 'Research Papers',
    description: 'Academic papers with citations and field tags.',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'authors', label: 'Authors' },
      { key: 'venue', label: 'Venue' },
      { key: 'date', label: 'Publication date' },
      { key: 'citations', label: 'Citations' },
      { key: 'field', label: 'Field' },
    ],
    rows: researchRows,
    getSidebarModel: (row) => ({
      title: String(row.title),
      fields: [
        { label: 'Authors', value: row.authors },
        { label: 'Venue', value: row.venue },
        { label: 'Date', value: row.date },
        { label: 'Citations', value: row.citations },
        { label: 'Field', value: row.field },
      ],
      summary: String(row.summary),
    }),
  },
];

export const getDemoTabById = (id: DemoTabId) =>
  demoTabs.find((tab) => tab.id === id) ?? demoTabs[0];

export const assertDemoTabs = (tabs: DemoTabConfig[]) => {
  if (process.env.NODE_ENV === 'production') return;
  tabs.forEach((tab, index) => {
    if (!tab.id || !tab.label) {
      throw new Error(`Demo tab missing id/label at index ${index}`);
    }
    if (!Array.isArray(tab.columns) || tab.columns.length === 0) {
      throw new Error(`Demo tab ${tab.id} has no columns`);
    }
    if (!Array.isArray(tab.rows) || tab.rows.length === 0) {
      throw new Error(`Demo tab ${tab.id} has no rows`);
    }
    tab.rows.forEach((row, rowIndex) => {
      if (!row.id) {
        throw new Error(`Demo tab ${tab.id} row missing id at ${rowIndex}`);
      }
    });
  });
};
